version: "2"

x-postgres-env: &postgres-env
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    POSTGRES_DB: games

services:
    postgres:
      restart: always
      image: postgres:14
      container_name: postgres
      ports:
        - "5433:5432"
      environment:
        <<: *postgres-env
      volumes:
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        
    grpc-server:
      restart: always
      image: docker.io/teledima/grpc-server
      environment:
        POSTGRES_HOST: postgres
        POSTGRES_PORT: 5432
        <<: *postgres-env
      ports:
        - "5001:5001"
      depends_on: [postgres]
