apiVersion: v1
kind: Pod
metadata: 
  name: grpc-pod
  labels:
    app: grpc-service
spec:

  restartPolicy: Always
  volumes:
  - name: postgres-claim
    emptyDir: {} 

  containers:
    - image: debian
      name: debian
      volumeMounts:
        - name: postgres-claim
          mountPath: /
      command: ["/bin/sh"]
      args: ["-c", "apt-get update && apt-get upgrade -y && apt-get install curl -y && curl https://raw.githubusercontent.com/teledima/grpc-laba/master/init.sql > init.sql"]
  
    - image: postgres:14
      name: postgres
      env:
        - name: POSTGRES_DB
          value: games
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_USER
          value: postgres
      ports:
        - containerPort: 5432
      resources: {}
      volumeMounts:
        - mountPath: /docker-entrypoint-initdb.d/init.sql
          name: postgres-claim
    
    - image: docker.io/teledima/grpc-server:v1
      name: grpc-server
      env:
        - name: POSTGRES_DB
          value: games
        - name: POSTGRES_HOST
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_USER
          value: postgres
      ports:
        - containerPort: 5001
